export interface Tour {
    id: string
    title: string
    subtitle: string
    days: number
    dates: string[]
    image: string
    gradient: string
    description: string
    highlights: string[]
    itinerary: {
        day: number
        title: string
        description: string
        activities: string[]
        image?: string
        meals?: string
    }[]
    inclusions: string[]
    exclusions: string[]
    price: {
        perPerson: number
        currency: string
    }
    status: "upcoming" | "past"
}

export const tours: Tour[] = [
    {
        id: "spain-portugal",
        title: "SPLENDID",
        subtitle: "SPAIN AND PORTUGAL",
        days: 14,
        dates: ["22 AUGUST 2026"],
        image: "/tour_spain_portugal.png",
        gradient: "from-cyan-400 to-blue-500",
        description:
            "Embark on an unforgettable journey through the Iberian Peninsula, exploring the rich history, stunning architecture, and vibrant culture of Spain and Portugal.",
        highlights: [
            "Visit the iconic Sagrada Familia in Barcelona",
            "Explore the historic Alhambra Palace in Granada",
            "Discover Lisbon's charming neighborhoods",
            "Experience authentic Flamenco in Seville",
            "Wine tasting in Porto's Douro Valley",
        ],
        itinerary: [
            {
                day: 1,
                title: "Arrival in Barcelona",
                description: "Welcome to Spain! Arrive in Barcelona and transfer to your hotel.",
                activities: [
                    "Airport pickup and hotel check-in",
                    "Welcome dinner at a traditional Catalan restaurant",
                    "Evening stroll along Las Ramblas",
                ],
            },
            {
                day: 2,
                title: "Barcelona City Tour",
                description: "Explore the architectural wonders of Barcelona",
                activities: [
                    "Visit Sagrada Familia and Park Güell",
                    "Gothic Quarter walking tour",
                    "Lunch at La Boqueria Market",
                    "Evening at Barceloneta Beach",
                ],
            },
            {
                day: 3,
                title: "Barcelona to Valencia",
                description: "Journey south to the coastal city of Valencia",
                activities: [
                    "Morning departure to Valencia",
                    "City of Arts and Sciences tour",
                    "Traditional paella cooking class",
                    "Sunset at Malvarrosa Beach",
                ],
            },
            {
                day: 4,
                title: "Valencia to Granada",
                description: "Travel to the historic city of Granada",
                activities: [
                    "Scenic drive through Spanish countryside",
                    "Arrival and hotel check-in",
                    "Evening tapas tour in Albaicín",
                    "Flamenco show",
                ],
            },
            {
                day: 5,
                title: "Alhambra Palace",
                description: "Discover the magnificent Moorish palace",
                activities: [
                    "Guided tour of Alhambra and Generalife Gardens",
                    "Free afternoon for shopping",
                    "Sunset views from Mirador de San Nicolás",
                ],
            },
            {
                day: 6,
                title: "Granada to Seville",
                description: "Head to the heart of Andalusia",
                activities: [
                    "Morning departure to Seville",
                    "Seville Cathedral and Giralda Tower visit",
                    "Royal Alcázar tour",
                    "Evening river cruise on Guadalquivir",
                ],
            },
            {
                day: 7,
                title: "Seville Exploration",
                description: "Full day discovering Seville's charm",
                activities: [
                    "Plaza de España and Maria Luisa Park",
                    "Triana neighborhood and ceramic workshops",
                    "Authentic Flamenco performance",
                    "Tapas dinner in Santa Cruz",
                ],
            },
            {
                day: 8,
                title: "Seville to Lisbon",
                description: "Cross into Portugal",
                activities: [
                    "Scenic drive to Lisbon",
                    "Afternoon arrival and hotel check-in",
                    "Evening at Bairro Alto",
                    "Fado music performance",
                ],
            },
            {
                day: 9,
                title: "Lisbon City Tour",
                description: "Explore Portugal's captivating capital",
                activities: [
                    "Belém Tower and Jerónimos Monastery",
                    "Taste famous Pastéis de Belém",
                    "Alfama district walking tour",
                    "Tram 28 experience",
                ],
            },
            {
                day: 10,
                title: "Sintra Day Trip",
                description: "Visit the fairy-tale town of Sintra",
                activities: [
                    "Pena Palace tour",
                    "Quinta da Regaleira exploration",
                    "Cabo da Roca (westernmost point of Europe)",
                    "Return to Lisbon",
                ],
            },
            {
                day: 11,
                title: "Lisbon to Porto",
                description: "Journey to Portugal's second city",
                activities: [
                    "Morning departure to Porto",
                    "Stop at Coimbra University",
                    "Arrival in Porto and hotel check-in",
                    "Evening at Ribeira district",
                ],
            },
            {
                day: 12,
                title: "Porto Exploration",
                description: "Discover the charm of Porto",
                activities: [
                    "Port wine cellar tour and tasting",
                    "Livraria Lello bookstore visit",
                    "Clérigos Tower climb",
                    "Douro River cruise",
                ],
            },
            {
                day: 13,
                title: "Douro Valley",
                description: "Wine country excursion",
                activities: [
                    "Full-day Douro Valley tour",
                    "Visit two wine estates",
                    "Traditional Portuguese lunch",
                    "Scenic train ride",
                ],
            },
            {
                day: 14,
                title: "Departure",
                description: "Farewell to the Iberian Peninsula",
                activities: [
                    "Leisure morning in Porto",
                    "Last-minute shopping",
                    "Airport transfer",
                    "Departure with unforgettable memories",
                ],
            },
        ],
        inclusions: [
            "13 nights accommodation in 4-star hotels",
            "Daily breakfast and 10 dinners",
            "All transfers and transportation in AC coach",
            "Professional English-speaking guide",
            "All entrance fees to mentioned attractions",
            "Port wine tasting in Porto",
            "Flamenco show in Seville",
            "Fado performance in Lisbon",
        ],
        exclusions: [
            "International flights",
            "Travel insurance",
            "Lunches (except where specified)",
            "Personal expenses and tips",
            "Optional activities",
        ],
        price: {
            perPerson: 185000,
            currency: "INR",
        },
        status: "upcoming",
    },
    {
        id: "kenya-safari",
        title: "KENYA",
        subtitle: "SAFARI",
        days: 9,
        dates: ["17 JULY 2026", "8 AUGUST 2026", "4 SEPTEMBER 2026"],
        image: "/tour_kenya_safari.png",
        gradient: "from-purple-400 via-pink-400 to-orange-400",
        description:
            "Experience the ultimate African safari adventure in Kenya. Witness the Great Migration, spot the Big Five, and immerse yourself in the stunning landscapes of East Africa.",
        highlights: [
            "Witness the Great Wildebeest Migration",
            "Spot the Big Five in Masai Mara",
            "Visit a traditional Maasai village",
            "Sunrise hot air balloon safari",
            "Game drives in multiple national parks",
        ],
        itinerary: [
            {
                day: 1,
                title: "Arrival in Nairobi",
                description: "Welcome to Kenya!",
                activities: [
                    "Arrive at Jomo Kenyatta International Airport",
                    "Meet and greet by our representative",
                    "Transfer to hotel in Nairobi",
                    "Welcome briefing and dinner",
                ],
            },
            {
                day: 2,
                title: "Nairobi to Amboseli",
                description: "Journey to Amboseli National Park",
                activities: [
                    "Early breakfast and departure",
                    "Scenic drive to Amboseli (4 hours)",
                    "Lunch at the lodge",
                    "Afternoon game drive with views of Mt. Kilimanjaro",
                ],
            },
            {
                day: 3,
                title: "Amboseli Full Day",
                description: "Explore Amboseli's elephant herds",
                activities: [
                    "Early morning game drive",
                    "Return to lodge for breakfast",
                    "Leisure time at the lodge",
                    "Afternoon game drive",
                    "Sundowner experience",
                ],
            },
            {
                day: 4,
                title: "Amboseli to Lake Nakuru",
                description: "Travel to the Great Rift Valley",
                activities: [
                    "Morning game drive and breakfast",
                    "Drive to Lake Nakuru (6 hours)",
                    "Lunch en route",
                    "Evening arrival and relaxation",
                ],
            },
            {
                day: 5,
                title: "Lake Nakuru to Masai Mara",
                description: "Head to the world-famous Masai Mara",
                activities: [
                    "Early morning game drive at Lake Nakuru",
                    "Spot flamingos and rhinos",
                    "Drive to Masai Mara (5 hours)",
                    "Evening game drive in Masai Mara",
                ],
            },
            {
                day: 6,
                title: "Masai Mara Full Day",
                description: "Full day safari in Masai Mara",
                activities: [
                    "Optional hot air balloon safari at sunrise",
                    "Full-day game drive with picnic lunch",
                    "Search for the Big Five",
                    "Witness the Great Migration (seasonal)",
                ],
            },
            {
                day: 7,
                title: "Masai Mara Experience",
                description: "Another day in paradise",
                activities: [
                    "Early morning game drive",
                    "Return to lodge for breakfast",
                    "Visit to Maasai village",
                    "Afternoon game drive",
                    "Bush dinner under the stars",
                ],
            },
            {
                day: 8,
                title: "Masai Mara to Nairobi",
                description: "Return to Nairobi",
                activities: [
                    "Final early morning game drive",
                    "Breakfast at the lodge",
                    "Drive back to Nairobi (5-6 hours)",
                    "Farewell dinner at Carnivore Restaurant",
                ],
            },
            {
                day: 9,
                title: "Departure",
                description: "Safari memories to last a lifetime",
                activities: [
                    "Leisure morning (day room available)",
                    "Optional Nairobi city tour",
                    "Transfer to airport",
                    "Departure",
                ],
            },
        ],
        inclusions: [
            "8 nights accommodation (mix of lodges and tented camps)",
            "All meals as per itinerary",
            "All game drives in 4x4 safari vehicles",
            "Professional safari guide",
            "Park entrance fees",
            "Maasai village visit",
            "Airport transfers",
            "Bottled water during game drives",
        ],
        exclusions: [
            "International flights",
            "Kenya visa fees",
            "Travel insurance",
            "Hot air balloon safari (optional, USD 450 per person)",
            "Tips for guides and lodge staff",
            "Personal expenses",
        ],
        price: {
            perPerson: 165000,
            currency: "INR",
        },
        status: "past",
    },
    {
        id: "canadian-rockies",
        title: "ALASKA AND",
        subtitle: "CANADIAN ROCKIES",
        days: 17,
        dates: ["15 JUNE 2026"],
        image: "/tour_canadian_rockies.png",
        gradient: "from-teal-400 to-cyan-500",
        description:
            "Discover the breathtaking beauty of the Canadian Rockies and Alaska. From turquoise lakes to massive glaciers, this journey showcases nature at its finest.",
        highlights: [
            "Visit stunning Moraine Lake and Lake Louise",
            "Explore Banff and Jasper National Parks",
            "Glacier cruise in Alaska",
            "Wildlife spotting opportunities",
            "Scenic train journey through the Rockies",
        ],
        itinerary: [
            {
                day: 1,
                title: "Arrival in Calgary",
                description: "Welcome to Canada!",
                activities: [
                    "Arrive at Calgary International Airport",
                    "Transfer to hotel",
                    "Orientation meeting",
                    "Welcome dinner",
                ],
            },
            {
                day: 2,
                title: "Calgary to Banff",
                description: "Journey to the heart of the Rockies",
                activities: [
                    "Scenic drive to Banff (1.5 hours)",
                    "Banff Gondola ride to Sulphur Mountain",
                    "Explore Banff town",
                    "Evening at leisure",
                ],
            },
            {
                day: 3,
                title: "Lake Louise & Moraine Lake",
                description: "Visit the most beautiful lakes in Canada",
                activities: [
                    "Early morning visit to Moraine Lake",
                    "Canoeing on Lake Louise",
                    "Fairmont Chateau Lake Louise tour",
                    "Hiking options available",
                ],
            },
            {
                day: 4,
                title: "Icefields Parkway",
                description: "One of the world's most scenic drives",
                activities: [
                    "Drive along Icefields Parkway",
                    "Columbia Icefield experience",
                    "Glacier Skywalk",
                    "Athabasca Falls",
                ],
            },
            {
                day: 5,
                title: "Jasper National Park",
                description: "Explore Jasper's wilderness",
                activities: [
                    "Maligne Lake cruise to Spirit Island",
                    "Maligne Canyon walk",
                    "Jasper town exploration",
                    "Optional wildlife tour",
                ],
            },
            {
                day: 6,
                title: "Jasper to Vancouver",
                description: "Scenic train journey",
                activities: [
                    "Board Rocky Mountaineer train",
                    "Full-day scenic rail journey",
                    "Gourmet meals on board",
                    "Arrive in Vancouver evening",
                ],
            },
            {
                day: 7,
                title: "Vancouver City Tour",
                description: "Discover beautiful Vancouver",
                activities: [
                    "Stanley Park and Seawall",
                    "Granville Island",
                    "Gastown and Chinatown",
                    "Capilano Suspension Bridge",
                ],
            },
            {
                day: 8,
                title: "Vancouver to Juneau",
                description: "Fly to Alaska's capital",
                activities: [
                    "Flight to Juneau",
                    "Mendenhall Glacier visit",
                    "Downtown Juneau exploration",
                    "Salmon bake dinner",
                ],
            },
            {
                day: 9,
                title: "Juneau Adventures",
                description: "Alaska wilderness experience",
                activities: [
                    "Whale watching tour",
                    "Glacier helicopter tour (optional)",
                    "Alaska State Museum",
                    "Free evening",
                ],
            },
            {
                day: 10,
                title: "Juneau to Skagway",
                description: "Gold Rush history",
                activities: [
                    "Ferry to Skagway",
                    "White Pass & Yukon Route Railway",
                    "Historic downtown walking tour",
                    "Gold Rush museum",
                ],
            },
            {
                day: 11,
                title: "Glacier Bay",
                description: "UNESCO World Heritage Site",
                activities: [
                    "Full-day Glacier Bay cruise",
                    "Witness calving glaciers",
                    "Wildlife spotting (whales, seals, bears)",
                    "Park ranger narration",
                ],
            },
            {
                day: 12,
                title: "Skagway to Anchorage",
                description: "Alaska's largest city",
                activities: [
                    "Flight to Anchorage",
                    "City tour",
                    "Alaska Native Heritage Center",
                    "Dinner at a local restaurant",
                ],
            },
            {
                day: 13,
                title: "Denali National Park",
                description: "Home of North America's tallest peak",
                activities: [
                    "Drive to Denali (4 hours)",
                    "Afternoon arrival",
                    "Visitor center exploration",
                    "Evening ranger program",
                ],
            },
            {
                day: 14,
                title: "Denali Exploration",
                description: "Wildlife and wilderness",
                activities: [
                    "Full-day Denali bus tour",
                    "Wildlife viewing opportunities",
                    "Views of Denali (weather permitting)",
                    "Picnic lunch in the park",
                ],
            },
            {
                day: 15,
                title: "Denali to Seward",
                description: "Coastal Alaska",
                activities: [
                    "Scenic drive to Seward",
                    "Stop at Portage Glacier",
                    "Alaska SeaLife Center",
                    "Evening in Seward",
                ],
            },
            {
                day: 16,
                title: "Kenai Fjords",
                description: "Glacier cruise adventure",
                activities: [
                    "Full-day Kenai Fjords cruise",
                    "See tidewater glaciers",
                    "Marine wildlife viewing",
                    "Return to Anchorage",
                ],
            },
            {
                day: 17,
                title: "Departure",
                description: "Farewell to the Great North",
                activities: [
                    "Leisure morning",
                    "Last-minute shopping",
                    "Airport transfer",
                    "Departure with incredible memories",
                ],
            },
        ],
        inclusions: [
            "16 nights accommodation in premium hotels",
            "Daily breakfast and 12 dinners",
            "Rocky Mountaineer train journey (1 day)",
            "All transfers and transportation",
            "Professional tour guide",
            "All entrance fees to national parks",
            "Glacier Bay cruise",
            "Kenai Fjords cruise",
            "Banff Gondola",
            "Columbia Icefield experience",
        ],
        exclusions: [
            "International flights",
            "Domestic flights (Vancouver-Juneau, Skagway-Anchorage)",
            "Travel insurance",
            "Lunches (except where specified)",
            "Optional activities (helicopter tours, etc.)",
            "Personal expenses and tips",
        ],
        price: {
            perPerson: 425000,
            currency: "INR",
        },
        status: "past",
    },
    {
        id: "arunachal-kaziranga",
        title: "ADVENTUROUS",
        subtitle: "ARUNACHAL & KAZIRANGA",
        days: 10,
        dates: ["4 APRIL 2026"],
        image: "/tour_arunachal_kaziranga.png",
        gradient: "from-yellow-400 via-orange-400 to-red-500",
        description:
            "Embark on an adventurous journey through the mystical lands of Arunachal Pradesh and the wildlife haven of Kaziranga. Experience the rich Buddhist culture, breathtaking Himalayan landscapes, and encounter the famous one-horned rhinoceros in their natural habitat.",
        highlights: [
            "Visit the iconic Tawang Monastery - largest in India",
            "Explore the stunning Sela Pass at 13,700 feet",
            "Witness the majestic one-horned rhinos at Kaziranga",
            "Experience authentic Buddhist culture and traditions",
            "Jeep safari through Kaziranga National Park",
            "Visit Bumla Pass near Indo-China border",
            "Discover the beautiful Nuranang Waterfall",
        ],
        itinerary: [
            {
                day: 1,
                title: "Arrival in Guwahati",
                description: "Welcome to the Gateway of Northeast India. Upon arrival at Guwahati Airport, guests receive a warm welcome with traditional garlands and a refreshing water bottle for comfort. An English-speaking guide accompanies the group, offering assistance and insights throughout the day. Enjoy a delicious non-vegetarian lunch at a reputed Indian restaurant, followed by a relaxing evening and a comforting non-vegetarian dinner at another Indian restaurant.",
                image: "/arunachal_day1.png",
                meals: "Lunch - Dinner",
                activities: [
                    "Arrive at Lokpriya Gopinath Bordoloi International Airport",
                    "Meet and greet by our representative",
                    "Transfer to hotel in Guwahati",
                    "Evening visit to Kamakhya Temple (optional)",
                    "Welcome dinner with traditional Assamese cuisine",
                ],
            },
            {
                day: 2,
                title: "Guwahati to Tezpur to Dirang",
                description: "Journey towards the mountains through the scenic landscapes of Assam and Arunachal Pradesh. Drive through lush tea gardens, traditional villages with colorful houses, and misty hills. Cross into Arunachal Pradesh and experience the transition from plains to mountains as you ascend towards Dirang.",
                image: "/arunachal_day2.png",
                meals: "Breakfast - Lunch - Dinner",
                activities: [
                    "Early morning departure to Dirang (8-9 hours)",
                    "Drive through scenic tea gardens and villages",
                    "Stop at Tezpur for lunch",
                    "Cross into Arunachal Pradesh",
                    "Evening arrival at Dirang",
                    "Check-in to hotel and relaxation",
                ],
            },
            {
                day: 3,
                title: "Dirang to Tawang",
                description: "Cross the magnificent Sela Pass at 13,700 feet, one of the highest motorable passes in the world. Experience breathtaking views of snow-capped mountains, frozen lakes, and colorful prayer flags. Stop at the beautiful Sela Lake and pay respects at the Jaswant Garh War Memorial before arriving in the spiritual town of Tawang.",
                image: "/arunachal_day3.png",
                meals: "Breakfast - Lunch - Dinner",
                activities: [
                    "Early breakfast and departure",
                    "Visit Dirang Dzong (fort)",
                    "Drive through Sela Pass (13,700 ft) with photo stops",
                    "Visit Paradise Lake (Sela Lake)",
                    "Stop at Jaswant Garh War Memorial",
                    "Arrive in Tawang by evening",
                    "Overnight at Tawang",
                ],
            },
            {
                day: 4,
                title: "Tawang Monastery & Local Sightseeing",
                description: "Explore the spiritual heart of Tawang with a visit to the magnificent Tawang Monastery, the largest Buddhist monastery in India. Built in the 17th century, this architectural marvel houses ancient scriptures, beautiful murals, and a stunning golden Buddha statue. Experience the peaceful atmosphere as monks chant their prayers and prayer flags flutter in the mountain breeze.",
                image: "/arunachal_day4.png",
                meals: "Breakfast - Lunch - Dinner",
                activities: [
                    "Visit Tawang Monastery - largest in India",
                    "Explore the monastery museum and library",
                    "Visit the Giant Buddha statue",
                    "Tawang War Memorial visit",
                    "Explore local markets",
                    "Evening at leisure",
                ],
            },
            {
                day: 5,
                title: "Bumla Pass Excursion",
                description: "Visit the Indo-China border at Bumla Pass, situated at an altitude of 15,200 feet. This high-altitude adventure takes you to one of the most strategic border points, offering stunning views of snow-covered peaks and the beautiful turquoise Madhuri Lake (Sangetsar Lake). Stop at the magnificent Nuranang Waterfall on your return journey.",
                image: "/arunachal_day5.png",
                meals: "Breakfast - Lunch - Dinner",
                activities: [
                    "Early morning drive to Bumla Pass (15,200 ft)",
                    "Visit Madhuri Lake (Sangetsar Lake)",
                    "Photo opportunities at the border",
                    "Return to Tawang",
                    "Visit Nuranang Waterfall en route",
                    "Evening cultural program (if available)",
                ],
            },
            {
                day: 6,
                title: "Tawang to Bomdila",
                description: "Return journey through the mountains with a scenic drive back through Sela Pass. Arrive in the charming town of Bomdila, known for its beautiful monastery and local handicraft center. Experience the peaceful mountain town atmosphere and interact with local artisans.",
                image: "/arunachal_day6.png",
                meals: "Breakfast - Lunch - Dinner",
                activities: [
                    "Morning departure from Tawang",
                    "Scenic drive back through Sela Pass",
                    "Arrive in Bomdila",
                    "Visit Bomdila Monastery",
                    "Explore local craft center",
                    "Overnight at Bomdila",
                ],
            },
            {
                day: 7,
                title: "Bomdila to Kaziranga",
                description: "Journey from the Himalayan foothills to the lush plains of Assam. Experience the dramatic landscape transition as you descend through forests, tea estates, and rural villages. Arrive at Kaziranga National Park, a UNESCO World Heritage Site and home to the world's largest population of one-horned rhinoceros.",
                image: "/arunachal_day7.png",
                meals: "Breakfast - Lunch - Dinner",
                activities: [
                    "Early morning departure to Kaziranga (7-8 hours)",
                    "Descend from mountains to plains",
                    "Lunch en route",
                    "Arrive at Kaziranga National Park",
                    "Check-in to resort",
                    "Evening briefing about safari",
                ],
            },
            {
                day: 8,
                title: "Kaziranga National Park - Full Day",
                description: "Experience the thrill of wildlife safaris in Kaziranga National Park, home to the world's largest population of one-horned rhinoceros. Start with an early morning elephant safari to get up close with rhinos in their natural habitat, followed by an exciting jeep safari through the grasslands where you can spot wild elephants, water buffaloes, deer, and numerous bird species.",
                image: "/arunachal_day8.png",
                meals: "Breakfast - Lunch - Dinner",
                activities: [
                    "Early morning elephant safari (Central Range)",
                    "Breakfast at resort",
                    "Jeep safari in Western Range",
                    "Spot one-horned rhinos, elephants, and birds",
                    "Visit Kaziranga Orchid Park",
                    "Evening at leisure",
                ],
            },
            {
                day: 9,
                title: "Kaziranga to Guwahati",
                description: "Return to Guwahati with optional morning safari. Enjoy a relaxing evening cruise on the mighty Brahmaputra River, visiting the Umananda Temple on Peacock Island. Watch the beautiful sunset over the river while spotting river dolphins and enjoying the peaceful atmosphere of this sacred river.",
                image: "/arunachal_day9.png",
                meals: "Breakfast - Lunch - Dinner",
                activities: [
                    "Optional early morning jeep safari",
                    "Breakfast and check-out",
                    "Drive back to Guwahati (4-5 hours)",
                    "Cruise on Brahmaputra River (evening)",
                    "Visit Umananda Temple on Peacock Island",
                    "Farewell dinner",
                ],
            },
            {
                day: 10,
                title: "Departure from Guwahati",
                description: "Journey ends with beautiful memories of the mountains and wildlife. Enjoy a leisurely morning with optional shopping at local markets where you can buy traditional Assamese silk, handicrafts, and souvenirs. Transfer to the airport for your onward journey, carrying unforgettable memories of Northeast India.",
                image: "/arunachal_day10.png",
                meals: "Breakfast",
                activities: [
                    "Leisure morning",
                    "Last-minute shopping at local markets",
                    "Transfer to airport",
                    "Departure with unforgettable memories",
                ],
            },
        ],
        inclusions: [
            "11 nights accommodation (hotels and resorts)",
            "All meals - breakfast, lunch, and dinner",
            "All transfers in comfortable vehicles",
            "Experienced driver and tour guide",
            "All permits for Arunachal Pradesh",
            "Elephant safari at Kaziranga",
            "2 Jeep safaris at Kaziranga National Park",
            "All entrance fees and monument charges",
            "Brahmaputra River cruise",
        ],
        exclusions: [
            "Flights to/from Guwahati",
            "Travel insurance",
            "Camera fees at monuments",
            "Personal expenses and tips",
            "Any meals not mentioned in inclusions",
            "Optional activities",
        ],
        price: {
            perPerson: 75000,
            currency: "INR",
        },
        status: "upcoming",
    },
]
